`timescale 1ns / 1ps
module alu(
    input [31:0] a,
	 input [31:0] b,
	 input [3:0] aluc,
	 output reg [31:0] r,
	 output reg zero,
	 output reg carry,
	 output reg negative,
	 output reg overflow
    );
reg [32:0] extend=0 ;
    always@(*)
    begin
       zero=0;
       carry=0;
       negative=0;
       overflow=0;
       casex(aluc)
              4'b0000://无符号加
                   begin
                      extend=a+b;
                      r=extend[31:0];
                      if(r==0)
                        zero=1;
                      else
                        zero=0;
                      if(extend[32]==1)
                        carry=1;
                      if(r[31]==1)
                        negative=1;
                   end                       
              4'b0001://无符号减
                   begin
                      r=a-b;
                      if(r==0)
                        zero=1;
                      else
                        zero=0;
                      if(r[31]==1)
                        negative=1; 
                      if(a<b)
                        carry=1;            
                      end
              4'b0010://有符号加
                      begin
                         extend=a+b;
                         r=extend[31:0];
                      if(r==0)
                        zero=1;
                      else
                        zero=0;
                      if(r[31]==1)
                          negative=1;
                      if(r[31]==0)
                          negative=0;  
                      if(a[31]==1 && b[31]==1 &&extend[32]==1&&extend[31]==0)
                          overflow=1;
                      if(a[31]==0 && b[31]==0 &&extend[31]==1)
                         overflow=1;                                  
                      end                             
              4'b0011://有符号减
                  begin
                    r=a-b;
                  if(r==0)
                    zero=1;
                  else
                    zero=0;
                  if(r[31]==1)
                    negative=1;
                  if(r[31]==0)
                    negative=0;
                  if(a[31]==1 && b[31]==0 && r[31]==0) 
                    overflow=1;     
                  if(a[31]==0 && b[31]==1 && r[31]==1) 
                    overflow=1;                
                  end
              4'b0100://And
                 begin
                   r=a&b;
                   if(r==0)
                     zero=1;
                   else
                     zero=0;
                   if(r[31]==1)
                     negative=1;                 
                 end
              4'b0101://Or
                 begin
                   r=a|b;
                 if(r==0)
                   zero=1;
                 else
                   zero=0;
                 if(r[31]==1)
                   negative=1;             
                 end
              4'b0110://Xor
                 begin
                   r=a^b;
                 if(r==0)
                   zero=1;
                 else
                   zero=0;
                 if(r[31]==1)
                   negative=1;             
                 end
              4'b0111://Nor
                 begin
                    r=~(a|b);
                 if(r==0)
                   zero=1;
                 else
                   zero=0;
                 if(r[31]==1)
                   negative=1;            
                 end
              4'b100x://Lui
                 begin
                   r={b[15:0],16'b0};
                  if(r==0)
                     zero=1;
                  else
                     zero=0;
                  if(r[31]==1)
                     negative=1;                   
                 end                                    
              4'b1010://Sltu
                  begin
                    r=(a<b)?1:0;
                  if(a-b==0)
                    zero =1;
                  if(a<b)
                    carry=1;
                  if(r[31]==1)
                    negative=1;
                  end
              4'b1011://Slu  有问题
                 begin
                  if(a[31]==0&&b[31]==0)
                    begin
                      r=(a<b)?1:0;
                     if(a-b==0)
                       zero =1;
                     if(a<b)
                       negative=1; 
                    end
                  if(a[31]==1&&b[31]==0) 
                    begin
                      r=1;
                     if(a-b==0)
                        zero =1;
                      negative=1;                  
                    end
                  if(a[31]==0&&b[31]==1) 
                      begin
                        r=0;
                       if(a-b==0)
                          zero =1;
                        negative=0;                  
                      end   
                  if(a[31]==1&&b[31]==1)
                      begin
                        r=(a<b)?1:0;
                      if(a-b==0)
                        zero =1;
                      if(a<b)
                        negative=1;                   
                      end           
                   end
              4'b1100://Sra
                  begin
                    case(a)
                    5'b00001:r={b[31],b[31:1]};
                    5'b00010:r={{2{b[31]}},b[31:2]};
                    5'b00011:r={{3{b[31]}},b[31:3]};
                    5'b00100:r={{4{b[31]}},b[31:4]}; 
                    5'b00101:r={{5{b[31]}},b[31:5]}; 
                    5'b00110:r={{6{b[31]}},b[31:6]}; 
                    5'b00111:r={{7{b[31]}},b[31:7]}; 
                    5'b01000:r={{8{b[31]}},b[31:8]}; 
                    5'b01001:r={{9{b[31]}},b[31:9]}; 
                    5'b01010:r={{10{b[31]}},b[31:10]}; 
                    5'b01011:r={{11{b[31]}},b[31:11]}; 
                    5'b01100:r={{12{b[31]}},b[31:12]}; 
                    5'b01101:r={{13{b[31]}},b[31:13]};
                    5'b01110:r={{14{b[31]}},b[31:14]}; 
                    5'b01111:r={{15{b[31]}},b[31:15]}; 
                    5'b10000:r={{16{b[31]}},b[31:16]}; 
                    5'b10001:r={{17{b[31]}},b[31:17]}; 
                    5'b10010:r={{18{b[31]}},b[31:18]}; 
                    5'b10011:r={{19{b[31]}},b[31:19]};  
                    5'b10100:r={{20{b[31]}},b[31:20]};
                    5'b10101:r={{21{b[31]}},b[31:21]};
                    5'b10110:r={{22{b[31]}},b[31:22]};
                    5'b10111:r={{23{b[31]}},b[31:23]};
                    5'b11000:r={{24{b[31]}},b[31:24]};
                    5'b11001:r={{25{b[31]}},b[31:25]};
                    5'b11010:r={{26{b[31]}},b[31:26]};
                    5'b11011:r={{27{b[31]}},b[31:27]};
                    5'b11100:r={{28{b[31]}},b[31:28]};
                    5'b11101:r={{29{b[31]}},b[31:29]};
                    5'b11110:r={{30{b[31]}},b[31:30]};
                    5'b11111:r={{31{b[31]}},b[31:31]};
                    default:r=b;                
                    endcase
                  if(r==0)
                      zero=1; 
                  else
                      zero=0; 
                  if(r[31]==1)
                     negative=1; 
                    carry=r[0];              
                  end
              4'b1101://Srl
                  begin
                  r=b>>a;
                  if(r==0)
                    zero=1; 
                  else
                    zero=0; 
                  if(r[31]==1)
                   negative=1; 
                  carry=r[0];                         
                  end
              4'b111x://Sll/Slr
                   begin
                   r=b<<a;
                  if(r==0)
                     zero=1; 
                  else
                     zero=0; 
                  if(r[31]==1)
                    negative=1;
                  carry=r[a];
                  end
              default:r=32'bz;
       endcase
    end
    endmodule