# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/vivado_projects/1552229-cpu31/1552229-cpu31.cache/wt [current_project]
set_property parent.project_path E:/vivado_projects/1552229-cpu31/1552229-cpu31.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet e:/vivado_projects/1552229-cpu31/1552229-cpu31.srcs/sources_1/ip/divu/divu.xci
set_property is_locked true [get_files e:/vivado_projects/1552229-cpu31/1552229-cpu31.srcs/sources_1/ip/divu/divu.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top divu -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all divu_

write_checkpoint -force -noxdef divu.dcp

catch { report_utilization -file divu_utilization_synth.rpt -pb divu_utilization_synth.pb }

if { [catch {
  file copy -force E:/vivado_projects/1552229-cpu31/1552229-cpu31.runs/divu_synth_1/divu.dcp e:/vivado_projects/1552229-cpu31/1552229-cpu31.srcs/sources_1/ip/divu/divu.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub e:/vivado_projects/1552229-cpu31/1552229-cpu31.srcs/sources_1/ip/divu/divu_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub e:/vivado_projects/1552229-cpu31/1552229-cpu31.srcs/sources_1/ip/divu/divu_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim e:/vivado_projects/1552229-cpu31/1552229-cpu31.srcs/sources_1/ip/divu/divu_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim e:/vivado_projects/1552229-cpu31/1552229-cpu31.srcs/sources_1/ip/divu/divu_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir E:/vivado_projects/1552229-cpu31/1552229-cpu31.ip_user_files/ip/divu]} {
  catch { 
    file copy -force e:/vivado_projects/1552229-cpu31/1552229-cpu31.srcs/sources_1/ip/divu/divu_stub.v E:/vivado_projects/1552229-cpu31/1552229-cpu31.ip_user_files/ip/divu
  }
}

if {[file isdir E:/vivado_projects/1552229-cpu31/1552229-cpu31.ip_user_files/ip/divu]} {
  catch { 
    file copy -force e:/vivado_projects/1552229-cpu31/1552229-cpu31.srcs/sources_1/ip/divu/divu_stub.vhdl E:/vivado_projects/1552229-cpu31/1552229-cpu31.ip_user_files/ip/divu
  }
}
