# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/vivado_projects/1552229-cpu31/1552229-cpu31.srcs/sources_1/ip/ipcore/ipcore.xci
# IP: The module: 'ipcore' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_projects/1552229-cpu31/1552229-cpu31.srcs/sources_1/ip/ipcore/ipcore_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ipcore'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/vivado_projects/1552229-cpu31/1552229-cpu31.srcs/sources_1/ip/ipcore/ipcore.xci
# IP: The module: 'ipcore' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_projects/1552229-cpu31/1552229-cpu31.srcs/sources_1/ip/ipcore/ipcore_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ipcore'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
